//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace FlutterwaveService
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ServiceSoap", Namespace = "http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ValidateCustomerNUBANOperationCompleted;

        private System.Threading.SendOrPostCallback ProcessPaymentRequestOperationCompleted;

        private System.Threading.SendOrPostCallback SettleMerchantTransactionsOperationCompleted;

        private System.Threading.SendOrPostCallback EncryptPasswordOperationCompleted;

        /// <remarks/>
        public Service()
        {
            this.Url = "http://localhost/Kola/Production/FluterWaveService/Service.asmx";
        }

        /// <remarks/>
        public event ValidateCustomerNUBANCompletedEventHandler ValidateCustomerNUBANCompleted;

        /// <remarks/>
        public event ProcessPaymentRequestCompletedEventHandler ProcessPaymentRequestCompleted;

        /// <remarks/>
        public event SettleMerchantTransactionsCompletedEventHandler SettleMerchantTransactionsCompleted;

        /// <remarks/>
        public event EncryptPasswordCompletedEventHandler EncryptPasswordCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateCustomerNUBAN", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ValidateCustomerNubanResponse ValidateCustomerNUBAN(ValidateRequest request)
        {
            object[] results = this.Invoke("ValidateCustomerNUBAN", new object[] {
                    request});
            return ((ValidateCustomerNubanResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginValidateCustomerNUBAN(ValidateRequest request, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ValidateCustomerNUBAN", new object[] {
                    request}, callback, asyncState);
        }

        /// <remarks/>
        public ValidateCustomerNubanResponse EndValidateCustomerNUBAN(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ValidateCustomerNubanResponse)(results[0]));
        }

        /// <remarks/>
        public void ValidateCustomerNUBANAsync(ValidateRequest request)
        {
            this.ValidateCustomerNUBANAsync(request, null);
        }

        /// <remarks/>
        public void ValidateCustomerNUBANAsync(ValidateRequest request, object userState)
        {
            if ((this.ValidateCustomerNUBANOperationCompleted == null))
            {
                this.ValidateCustomerNUBANOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateCustomerNUBANOperationCompleted);
            }
            this.InvokeAsync("ValidateCustomerNUBAN", new object[] {
                    request}, this.ValidateCustomerNUBANOperationCompleted, userState);
        }

        private void OnValidateCustomerNUBANOperationCompleted(object arg)
        {
            if ((this.ValidateCustomerNUBANCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateCustomerNUBANCompleted(this, new ValidateCustomerNUBANCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessPaymentRequest", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProcessPaymentResponse ProcessPaymentRequest(Request request)
        {
            object[] results = this.Invoke("ProcessPaymentRequest", new object[] {
                    request});
            return ((ProcessPaymentResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginProcessPaymentRequest(Request request, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ProcessPaymentRequest", new object[] {
                    request}, callback, asyncState);
        }

        /// <remarks/>
        public ProcessPaymentResponse EndProcessPaymentRequest(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ProcessPaymentResponse)(results[0]));
        }

        /// <remarks/>
        public void ProcessPaymentRequestAsync(Request request)
        {
            this.ProcessPaymentRequestAsync(request, null);
        }

        /// <remarks/>
        public void ProcessPaymentRequestAsync(Request request, object userState)
        {
            if ((this.ProcessPaymentRequestOperationCompleted == null))
            {
                this.ProcessPaymentRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessPaymentRequestOperationCompleted);
            }
            this.InvokeAsync("ProcessPaymentRequest", new object[] {
                    request}, this.ProcessPaymentRequestOperationCompleted, userState);
        }

        private void OnProcessPaymentRequestOperationCompleted(object arg)
        {
            if ((this.ProcessPaymentRequestCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessPaymentRequestCompleted(this, new ProcessPaymentRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SettleMerchantTransactions", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SettleMerchantTransactionsResponse SettleMerchantTransactions(Request request)
        {
            object[] results = this.Invoke("SettleMerchantTransactions", new object[] {
                    request});
            return ((SettleMerchantTransactionsResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSettleMerchantTransactions(Request request, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SettleMerchantTransactions", new object[] {
                    request}, callback, asyncState);
        }

        /// <remarks/>
        public SettleMerchantTransactionsResponse EndSettleMerchantTransactions(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((SettleMerchantTransactionsResponse)(results[0]));
        }

        /// <remarks/>
        public void SettleMerchantTransactionsAsync(Request request)
        {
            this.SettleMerchantTransactionsAsync(request, null);
        }

        /// <remarks/>
        public void SettleMerchantTransactionsAsync(Request request, object userState)
        {
            if ((this.SettleMerchantTransactionsOperationCompleted == null))
            {
                this.SettleMerchantTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSettleMerchantTransactionsOperationCompleted);
            }
            this.InvokeAsync("SettleMerchantTransactions", new object[] {
                    request}, this.SettleMerchantTransactionsOperationCompleted, userState);
        }

        private void OnSettleMerchantTransactionsOperationCompleted(object arg)
        {
            if ((this.SettleMerchantTransactionsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SettleMerchantTransactionsCompleted(this, new SettleMerchantTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EncryptPassword", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EncryptPassword(string Value, string key)
        {
            object[] results = this.Invoke("EncryptPassword", new object[] {
                    Value,
                    key});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEncryptPassword(string Value, string key, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EncryptPassword", new object[] {
                    Value,
                    key}, callback, asyncState);
        }

        /// <remarks/>
        public string EndEncryptPassword(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void EncryptPasswordAsync(string Value, string key)
        {
            this.EncryptPasswordAsync(Value, key, null);
        }

        /// <remarks/>
        public void EncryptPasswordAsync(string Value, string key, object userState)
        {
            if ((this.EncryptPasswordOperationCompleted == null))
            {
                this.EncryptPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEncryptPasswordOperationCompleted);
            }
            this.InvokeAsync("EncryptPassword", new object[] {
                    Value,
                    key}, this.EncryptPasswordOperationCompleted, userState);
        }

        private void OnEncryptPasswordOperationCompleted(object arg)
        {
            if ((this.EncryptPasswordCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EncryptPasswordCompleted(this, new EncryptPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class ValidateRequest
    {

        private string customerIDField;

        private string nUBANField;

        private string transRefField;

        private string hashField;

        /// <remarks/>
        public string CustomerID
        {
            get
            {
                return this.customerIDField;
            }
            set
            {
                this.customerIDField = value;
            }
        }

        /// <remarks/>
        public string NUBAN
        {
            get
            {
                return this.nUBANField;
            }
            set
            {
                this.nUBANField = value;
            }
        }

        /// <remarks/>
        public string TransRef
        {
            get
            {
                return this.transRefField;
            }
            set
            {
                this.transRefField = value;
            }
        }

        /// <remarks/>
        public string hash
        {
            get
            {
                return this.hashField;
            }
            set
            {
                this.hashField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class Request
    {

        private string customerIDField;

        private string nUBANField;

        private string transRefField;

        private string settleTransRefField;

        private string hashField;

        private string merchantIDField;

        private string transCurrencyField;

        private string tokenCodeField;

        private double amountField;

        private int useHubAdvanceField;

        private int loanTenorField;

        private string transSourceField;

        private string remarksField;

        private string passwordField;

        private string userIDField;

        private System.DateTime tranxDateField;

        /// <remarks/>
        public string CustomerID
        {
            get
            {
                return this.customerIDField;
            }
            set
            {
                this.customerIDField = value;
            }
        }

        /// <remarks/>
        public string NUBAN
        {
            get
            {
                return this.nUBANField;
            }
            set
            {
                this.nUBANField = value;
            }
        }

        /// <remarks/>
        public string TransRef
        {
            get
            {
                return this.transRefField;
            }
            set
            {
                this.transRefField = value;
            }
        }

        /// <remarks/>
        public string SettleTransRef
        {
            get
            {
                return this.settleTransRefField;
            }
            set
            {
                this.settleTransRefField = value;
            }
        }

        /// <remarks/>
        public string hash
        {
            get
            {
                return this.hashField;
            }
            set
            {
                this.hashField = value;
            }
        }

        /// <remarks/>
        public string MerchantID
        {
            get
            {
                return this.merchantIDField;
            }
            set
            {
                this.merchantIDField = value;
            }
        }

        /// <remarks/>
        public string TransCurrency
        {
            get
            {
                return this.transCurrencyField;
            }
            set
            {
                this.transCurrencyField = value;
            }
        }

        /// <remarks/>
        public string TokenCode
        {
            get
            {
                return this.tokenCodeField;
            }
            set
            {
                this.tokenCodeField = value;
            }
        }

        /// <remarks/>
        public double Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        public int UseHubAdvance
        {
            get
            {
                return this.useHubAdvanceField;
            }
            set
            {
                this.useHubAdvanceField = value;
            }
        }

        /// <remarks/>
        public int LoanTenor
        {
            get
            {
                return this.loanTenorField;
            }
            set
            {
                this.loanTenorField = value;
            }
        }

        /// <remarks/>
        public string TransSource
        {
            get
            {
                return this.transSourceField;
            }
            set
            {
                this.transSourceField = value;
            }
        }

        /// <remarks/>
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime TranxDate
        {
            get
            {
                return this.tranxDateField;
            }
            set
            {
                this.tranxDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SettleMerchantTransactionsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessPaymentResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class ValidateCustomerNubanResponse
    {

        private string responseCodeField;

        private string responseDescField;

        private string customerIDField;

        private string nUBANField;

        private decimal hubAdvanceLimitField;

        private int maxTenorField;

        private string transRefField;

        private int tokenTypeField;

        private int intRateField;

        private string hashField;

        /// <remarks/>
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }

        /// <remarks/>
        public string ResponseDesc
        {
            get
            {
                return this.responseDescField;
            }
            set
            {
                this.responseDescField = value;
            }
        }

        /// <remarks/>
        public string CustomerID
        {
            get
            {
                return this.customerIDField;
            }
            set
            {
                this.customerIDField = value;
            }
        }

        /// <remarks/>
        public string NUBAN
        {
            get
            {
                return this.nUBANField;
            }
            set
            {
                this.nUBANField = value;
            }
        }

        /// <remarks/>
        public decimal HubAdvanceLimit
        {
            get
            {
                return this.hubAdvanceLimitField;
            }
            set
            {
                this.hubAdvanceLimitField = value;
            }
        }

        /// <remarks/>
        public int MaxTenor
        {
            get
            {
                return this.maxTenorField;
            }
            set
            {
                this.maxTenorField = value;
            }
        }

        /// <remarks/>
        public string TransRef
        {
            get
            {
                return this.transRefField;
            }
            set
            {
                this.transRefField = value;
            }
        }

        /// <remarks/>
        public int TokenType
        {
            get
            {
                return this.tokenTypeField;
            }
            set
            {
                this.tokenTypeField = value;
            }
        }

        /// <remarks/>
        public int IntRate
        {
            get
            {
                return this.intRateField;
            }
            set
            {
                this.intRateField = value;
            }
        }

        /// <remarks/>
        public string hash
        {
            get
            {
                return this.hashField;
            }
            set
            {
                this.hashField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class SettleMerchantTransactionsResponse : ValidateCustomerNubanResponse
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class ProcessPaymentResponse : ValidateCustomerNubanResponse
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void ValidateCustomerNUBANCompletedEventHandler(object sender, ValidateCustomerNUBANCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateCustomerNUBANCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ValidateCustomerNUBANCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ValidateCustomerNubanResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ValidateCustomerNubanResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void ProcessPaymentRequestCompletedEventHandler(object sender, ProcessPaymentRequestCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessPaymentRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ProcessPaymentRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ProcessPaymentResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ProcessPaymentResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void SettleMerchantTransactionsCompletedEventHandler(object sender, SettleMerchantTransactionsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SettleMerchantTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SettleMerchantTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public SettleMerchantTransactionsResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((SettleMerchantTransactionsResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void EncryptPasswordCompletedEventHandler(object sender, EncryptPasswordCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncryptPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EncryptPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

}